### ISSUE TITLE
Implement Webhook Handling

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/airgrab-interface#11]
## Description
Set up and handle webhook listeners to receive and process notifications from Fractal ID.

### Tasks:
1. Implement webhook listeners for Fractal's notifications.
2. Update our platform's UI in real-time based on the webhook data.
3. Authenticate webhook payloads using the X-Fractal-Signature header and our platform's secret token.

### Acceptance Criteria:
- [ ] Webhook listeners are functional and receiving data.
- [ ] UI updates in real-time based on webhook feedback.
- [ ] Webhook payloads are authenticated securely.
