### ISSUE TITLE
Implement Claim Submission & Transaction Monitoring

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/airgrab-interface#12]
## Description

This issue is to enable users to initiate claim processes. We will use the Merkle proof and Fractal ID proof, and users allocation amount to send a transaction to the on-chain airgrab contract which will execute the transactions to lock tokens for the user an return veTokens.

**Preparation & Submission**
Gather the 3 parameters - Fractal ID Proof, Merkle Proof, Allocation Amount
Prepare & send the transaction using wagmi usePrepareSendTransaction & useSendTransaction react hooks

**Montitoring**
Monitor the transaction using the useWaitForTransaction hook & update the UI accordingly  

**Error Handling**
We'll also need to handle any errors which may occur and make this information available to the user and update the UI to make the next steps clear should there be an error. 

### Tasks:

1. **Claim Submission**
   - Initiate the claim process on the contract using required parameters -  fractal KYC proof, merkel proof & Fractal ID

2. **Transaction Monitoring**
   - Implement functionality to continuously track the on-chain transaction.
   - Obtain and display the real-time status of the transaction to inform users about its progress.

### Acceptance Criteria:
- [ ] Users can successfully submit claims based on their selected method, with their associated Merkle proof and Fractal ID KYC proof.
- [ ] The platform continuously monitors on-chain transactions and provides feedback to users regarding the transaction status.
- [ ] Error are handled and feedback is provided to the user.
