### ISSUE TITLE
Setup Fractal Dashboard and Configuration

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/airgrab-interface#4]
## Description
Establish our platform's presence on the Fractal ID dashboard and configure necessary callbacks and parameters.

### Tasks:
1. Register and set up an application within the Fractal ID dashboard.
2. Define and input the Authorization & Verification callback URLs.
3. Configure block lists based on users' country residency and nationality.

### Acceptance Criteria:
- [x] Application set up successfully on the Fractal ID dashboard.
- [x] Callback URLs defined and configured correctly.
- [x] Block lists based on residency and nationality are defined.
- [x] Vercel is updated to include new environment variables for the production environment
- [x] Fractal ID's app name should be "MENTO Airdrop"

**Comment by baroooo** [comment]
@denviljclarke I don't think the Verification callback is used in our app, it is also not configurable on fractal production dashboard. can you confirm it is not needed?

**Comment by baroooo** [comment]
this is a duplicate of #399
closing this one and will continue tracking on the other issue
