### ISSUE TITLE
Integrate GCP Secrets and Update Development Scripts for Enhanced Workflow Consistency

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/airgrab-interface#45]
**Description**
To have a consistent workflow for development across our repos we want to add all the secrets required for development to our google could platform account along with a script to pull them down.  

**Tasks**
- [ ] Add relevant secrets based on based on the [env.example](https://github.com/mento-protocol/airgrab-interface/blob/8fa5d772a85f4a5d2502b48338c9400c0e2c1d74/.env.example) to our [GCP Secret Manager](https://console.cloud.google.com/security/secret-manager?project=mento-prod). ( You will need to temporarily request create permissions from Bayo / Bogdan)
- [ ] Add a script similar to [this script](https://github.com/mento-protocol/reserve-site/blob/dbf6bd29ef816938749a0abef8b47e4d61c746f4/scripts/get-secrets.sh) to get secrets added to GCP. 
- [ ] Update the package.json to include [this command](https://github.com/mento-protocol/reserve-site/blob/dbf6bd29ef816938749a0abef8b47e4d61c746f4/package.json#L21)
- [ ]   update the README with new instructions for local development [like this](https://github.com/mento-protocol/reserve-site/blob/dbf6bd29ef816938749a0abef8b47e4d61c746f4/package.json#L21)

**Acceptance Criteria**

- [ ] Script added along with command to run it
- [ ] Updated local development instructions to pull down secrets
- [ ] Verify successful retrieval of all necessary secrets for app functionality
