### ISSUE TITLE
Implement and Test Proof Generation Endpoint

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/airgrab-interface#7]
## Description
Implement and test the logic for the `/generate-proof` endpoint to generate a Merkle proof for a verified address and return proof. otherwise returns false. This will be used to verify an allocation exists for an address and retrieve proofs for valid addresses.

### Tasks:
1. Accept an address, and returns the merkle proof if the address is in the allocation list, otherwise returns false
2. Write test cases to validate Merkle proof generation, including scenarios of verified, unverified, and missing addresses

Implementation example [here](https://github.com/mento-protocol/merkle-tree-example)

### Acceptance Criteria:
- [ ] Merkle proof is generated and returned accurately for addresses in the allocation list.
- [ ] return false for addresses which are not in the allocation list.
- [ ] Proper error handling for addresses not present in the Merkle tree.
- [ ] All test cases run successfully?
