### ISSUE TITLE
Fractal ID Integration

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/airgrab-interface#8]
## Description

This issue captures getting Fractal ID integrated into the application. Users should be able to go through the flow as it's expected to be in the final version. Users will arrive on the page, connect their wallet, and sign a message to prove ownership. Once connected, the application will try to get a Fractal ID proof. If we can't, we'll direct the user to get signed up with Fractal. Once the user is finished on Fractal, they'll be redirected to use where we'll present them with the relevant information regarding their application status as Fractal provides it. 

### Tasks:

1. Define the basic structure and potential endpoints based on the Fractal ID requirements.
2. Implement routes to facilitate Fractal requirements (redirect and callback)
3. Implement routes for Fractal proof generation and Fractal link creation URL (Link used to redirect users to fractal populated with configuration information
4. Create a component to manage this KYC process. 

### Acceptance Criteria:

- [x] A clear structure and definition for potential endpoints related to Fractal ID. 
- [x] Route handler to redirect to Fractal.
- [x] Route handler for Fractal proof generation
- [x] Route hander to act as a redirect URL 
- [x] Route handler to act as a 'verified URL'
